= Ren'Py Color Utils
:toc:
:toclevels: 3

Provides a set of classes that represent colors in RGB, HSL, and HSV, and can be
converted between one-another freely.

The classes included in this package are all prefixed with the word `Fox` to
avoid conflict with other packages or Ren'Py builtin types.

== Usage

=== Included Functions

`hex_to_fox_rgb(hex) : FoxRGB`::
Function that converts a hex string into a `FoxRGB` class instance.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
| `hex`
| str
| A hex color string value constructed of a `#` character followed by 3, 4, 6,
or 8 hex digits.
|===
--


=== Included Classes

==== `FoxHSL`
Class representing a color value in HSL format.

This type may be constructed by providing a hue, saturation, ligntess, and
optionally alpha values.

.Example
[source, python]
----
FoxHSL(244, 0.76, 0.23)
# or
FoxHSL(244, 0.76, 0.23, 0.5)
----

===== Properties

`hue : int`::
Hue value as an int in the inclusive range `[0 -> 359]`

`saturation : float`::
Saturation value as a float in the inclusive range `[0.0 -> 1.0]`

`lightness : float`::
Lightness value as a float in the inclusive range `[0.0 -> 1.0]`

`alpha : float`::
Alpha value as a float in the inclusive range `[0.0 -> 1.0]`

`hsl : tuple[int, float, float]`::
A tuple containing the hue, saturation, and lightness values for the `FoxHSL`
value.

`hsla : tuple[int, float, float, float]`::
A tuple containing the hue, saturation, lightness, and alpha values for the
`FoxHSL` value.

`hsv : tuple[int, float, float]`::
A tuple containing the hue, saturation, and color value converted from the
`FoxHSL` instance.

`hsva : tuple[int, float, float, float]`::
A tuple containing the hue, saturation, value, and alpha values converted from
the `FoxHSL` instance.

`rgb : tuple[int, int, int]`::
A tuple containing the red, green, and blue channel values converted from the
`FoxHSL` instance.

`rgba : tuple[int, int, int, float]`::
A tuple containing the red, green, blue, and alpha channel values converted from
the `FoxHSL` instance.


===== Methods

`set_hue(hue)`::
Updates the hue on this `FoxHSL` instance to the given value.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
| `hue`
| int
| New hue value to set on the current `FoxHSL` instance.  This value should be
an `int` value in the inclusive range `[0 -> 359]`.  If it is not in that range
it will be rotated to be within that range while maintaining the target hue.
|===
--

`set_saturation(saturation)`::
Updates the saturation on this `FoxHSL` instance to the given value.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
| `saturation`
| float
| New saturation value to set on the current `FoxHSL` instance.  This value MUST
be a float value in the inclusive range `[0.0 -> 1.0]`.
|===
--

`set_lightness(lightness)`::
Updates the lightness on this `FoxHSL` instance to the given value.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
| `lightness`
| float
| New lightness value to set on the current `FoxHSL` instance.  This value MUST
be a float value in the inclusive range `[0.0 -> 1.0]`.
|===
--

`set_alpha(alpha)`::
Updates the alpha on this `FoxHSL` instance to the given value.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
| `alpha`
| float
| New alpha value to set on the current `FoxHSL` instance.  This value MUST be a
float value in the inclusive range `[0.0 -> 1.0]`.
|===
--

`to_hsl() : FoxHSL`::
Returns the current `FoxHSL` instance.

`to_hsv() : FoxHSV`::
Converts the current `FoxHSL` value into a FoxHSV value.

`to_rgb() : FoxRGB`::
Converts the current `FoxHSL` value into a FoxRGB value.

`with_hue(hue) : FoxHSL`::
Copies the target FoxHSL instance to a new FoxHSL instance with the given hue.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
| `hue`
| int
| Hue for the new `FoxHSL` instance.  Hue values should be `int` values in the
inclusive range `[0 -> 359]`.
|===
--

`with_saturation(saturation) : FoxHSL`::
Copies the target `FoxHSL` instance to a new `FoxHSL` instance with the given
saturation.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
| `saturation`
| float
| Saturation for the new `FoxHSL` instance.  Saturation values MUST be `float`
values in the inclusive range `[0.0 -> 1.0]`.
|===
--

`with_lightness(lightness) : FoxHSL`::
Copies the target `FoxHSL` instance to a new `FoxHSL` instance with the given
lightness.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
| `lightness`
| float
| Lightness for the new `FoxHSL` instance.  Lightness values MUST be float
values in the inclusive range `[0.0 -> 1.0]`.
|===
--

`with_alpha(alpha) : FoxHSL`::
Copies the target `FoxHSL` instance to a new `FoxHSL` instance with the given
lightness.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
| `alpha`
| float
| Alpha for the new `FoxHSL` instance.  Alpha values MUST be float values in the
inclusive range `[0.0 -> 1.0]`.
|===
--

`with_values(hue?, saturation?, lightness?, alpha?) : FoxHSL`::
Copies the target `FoxHSL` instance to a new `FoxHSL` instance with the given
values overriding the values from the target `FoxHSL` instance.  For example, a
copy could be created with a different hue and lightness, while keeping the
original saturation and alpha values.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
| `hue`
| int
| Optional hue override for the new `FoxHSL` instance.  If unset, or set to
`None`, the new `FoxHSL` will have the current instance's hue value.

| `saturation`
| float
| Optional saturation override for the new `FoxHSL` instance.  If unset, or set
to `None`, the new `FoxHSL` will have the current instance's saturation value.

| `lightness`
| float
| Optional lightness override for the new `FoxHSL` instance.  If unset, or set
to `None`, the new `FoxHSL` will have the current instance's lightness value.

| `alpha`
| float
| Optional alpha override for the new `FoxHSL` instance.  If unset, or set to
`None`, the new `FoxHSL` will have the curent instance's alpha value.
|===
--


==== `FoxHSV`
Class representing a color value in HSV format.

This type may be constructed by providing a hue, saturation, color value, and
optionally an alpha value.

[source, python]
----
FoxHSV(302, 0.9, 0.2)
# or
FoxHSV(302, 0.9, 0.2, 0.5)
----

===== Properties

`hue : int`::
Hue value as an int in the inclusive range `[0 -> 359]`.

`saturation : float`::
Saturation value as a float in the inclusive range `[0.0 -> 1.0]`.

`value : float`::
Color value as a float in the inclusive range `[0.0 -> 1.0]`.

`alpha : float`::
Alpha value as a float in the inclusive range `[0.0 -> 1.0]`.

`hsl : tuple[int, float, float]`::
A tuple containing the hue, saturation, and lightness values converted from the
`FoxHSV` instance.

`hsla : tuple[int, float, float, float]`::
A tuple containing the hue, saturation, lightness, and alpha values converted
from the `FoxHSV` instance.

`hsv : tuple[int, float, float]`::
A tuple containing the hue, saturation, and value from this `FoxHSV` instance.

`hsva : tuple[int, float, float, float]`::
A tuple containing the hue, saturation, value, and alpha values from the
`FoxHSV` instance.

`rgb : tuple[int, int, int]`::
A tuple containing the red, green, and blue channel values converted from the
`FoxHSV` instance.

`rgba : tuple[int, int, int, float]`::
A tuple containing the red, green, blue, and alpha channel values converted from
the `FoxHSV` instance.


===== Methods

`set_hue(hue)`::
Updates the hue on the current `FoxHSV` instance to the given value.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
| `hue`
| int
| Hue for the new `FoxHSV` instance.  Hue values should be `int` values in the
inclusive range `[0 -> 359]`.
|===
--

`set_saturation(saturation)`::
Updates the saturation on the current `FoxHSV` instance to the given value.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`set_value(value)`::
Updates the color value on the current `FoxHSV` instance to the given value.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`set_alpha(alpha)`::
Updates the alpha on the current `FoxHSV` instance to the given value.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`to_hsl() : FoxHSL`::
Converts the current `FoxHSV` value into a `FoxHSL` value.

`to_hsv() : FoxHSV`::
Returns the current `FoxHSV` value.

`to_rgb() : FoxRGB`::
Converts the current `FoxHSV` value into a `FoxRGB` value.

`with_hue(hue) : FoxHSV`::
Copies the target `FoxHSV` instance to a new `FoxHSV` instance with the given
hue.

`with_saturation(saturation) : FoxHSV`::
Copies the target `FoxHSV` instance to a new `FoxHSV` instance with the given
saturation.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`with_value(value) : FoxHSV`::
Copies the target `FoxHSV` instance to a new `FoxHSV` instance with the given
color value.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`with_alpha(value) : FoxHSV`::
Copies the target `FoxHSV` instance to a new `FoxHSV` instance with the given
alpha.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`with_values(hue?, saturation?, value?, alpha?) : FoxHSV`::
Copies the target `FoxHSV` instance to a new `FoxHSV` instance with the given
values overriding the values from the target `FoxHSV` instance.  For example,
a copy could be created with with a different hue and value, while keeping the
original saturation and alpha.
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--


==== `FoxRGB`
Class representing a color value in RGB format.

This type may be constructed by providing a red, green, blue, and optionally
alpha channel values.

[source, python]
----
FoxRGB(96, 221, 180)
# or
FoxRGB(96, 221, 180, 0.5)
----

===== Properties

`red : int`::
Red channel value as an int in the inclusive range `[0 -> 255]`.

`green : int`::
Green channel value as an int in the inclusive range `[0 -> 255]`.

`blue : int`::
Blue channel value as an int in the inclusive range `[0 -> 255]`.

`alpha : float`::
Alpha channel value as a float in the inclusive range `[0.0 -> 1.0]`.

`hsl : tuple[int, float, float]`::
A tuple containing the hue, saturation, and lightness values converted from the
`FoxRGB` instance.

`hsla : tuple[int, float, float, float]`::
A tuple containing the hue, saturation, lightness, and alpha values converted
from the `FoxRGB` instance.

`hsv : tuple[int, float, float]`::
A tuple containing the hue, saturation, and value converted from the `FoxRGB`
instance.

`hsva : tuple[int, float, float, float]`::
A tuple containing the hue, saturation, value, and alpha converted from the
`FoxRGB` instance.

`rgb : tuple[int, int, int]`::
A tuple containing the red, green, and blue channel values from the target
`FoxRGB` instance.

`rgba : tuple[int, int, int, float]`::
A tuple containing the red, green, blue, and alpha channel values from the
target `FoxRGB` instance.


===== Methods

`set_red(red)`::
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`set_green(green)`::
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`set_blue(blue)`::
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`set_alpha(alpha)`::
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`to_hsl()`::
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`to_hsv()`::
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`to_rgb()`::
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`with_red(red) : FoxRGB`::
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`with_green(green) : FoxRGB`::
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`with_blue(blue) : FoxRGB`::
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`with_alpha(alpha) : FoxRGB`::
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--

`with_values(red?, green?, blue?, alpha?) : FoxRGB`::
+
.Arguments
--
[cols="2h,2m,6a"]
|===
|===
--
